name: Get latest fits/cloudctl upstream release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' 
jobs:
  get-upstream-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch upstream release version
        run: |
          curl -sL https://api.github.com/repos/fi-ts/cloudctl/releases/latest | \
          jq -r ".tag_name" > release-versions/cloudctl-latest.txt
      - name: Set upstream relase version as pipline variable
        id: vars
        run: echo "version=$(sed 's/^v\(.*\)/\1/' release-versions/cloudctl-latest.txt )" >> $GITHUB_OUTPUT
      - name: Change upstream release version in cloudctl.rb
        env:
          VERSION: ${{ steps.vars.outputs.version }}
        run: sed -i 's/release = \".*\"/release = \"${{ steps.vars.outputs.version }}\"/' formula/cloudctl.rb
      - name: Check for modified files
        id: git-check
        run: echo modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true") >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'vmsimon'
          git config --global user.email 'vmsimon@users.noreply.github.com'
          git config --global push.followTags true
          git commit -am "New fi-ts/cloudctl release version"
          git tag -a "v${{ steps.vars.outputs.version }}" -m "Tag new fi-ts/cloudctl release version"
          git push
