name: Get latest fits/cloudctl upstream release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *' 
jobs:
  get-upstream-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch upstream release version
        id: release
        run: echo "version=$(curl -sL https://api.github.com/repos/fi-ts/cloudctl/releases/latest | jq -r ".tag_name" | sed 's/^v\(.*\)/\1/')" >> $GITHUB_OUTPUT
      - name: Change upstream release version in cloudctl.rb
        run: sed -i 's/release = \".*\"/release = \"${{ steps.release.outputs.version }}\"/' formula/cloudctl.rb
      - name: Check for modified files
        id: git-check
        run: echo modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true") >> $GITHUB_OUTPUT
      - name: Get SHA256 Hashes
        id: sha256
        run: for i in cloudctl-darwin-arm64 cloudctl-darwin-amd64 cloudctl-linux-amd64; do curl -fsSL https://github.com/fi-ts/cloudctl/releases/download/v0.11.13/$i -o $i; sha256sum $i | awk '{printf "%s=%s\n",$2,$1}' >> $GITHUB_OUTPUT ;done;
      - name: Show SHA256 Hashes
        run: for i in cloudctl-darwin-arm64 cloudctl-darwin-amd64 cloudctl-linux-amd64; do echo ${{steps.sha256.outputs.$i}}; done
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'vmsimon'
          git config --global user.email 'vmsimon@users.noreply.github.com'
          git config --global push.followTags true
          git commit -am "New fi-ts/cloudctl release version"
          git tag -a "v${{ steps.vars.outputs.version }}" -m "Tag new fi-ts/cloudctl release version"
          git push
